# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand((7, 7))
tensor

tensor([[0.7366, 0.3703, 0.9950, 0.8625, 0.7817, 0.0426, 0.7724],
        [0.4377, 0.9278, 0.8842, 0.2590, 0.1890, 0.8706, 0.4200],
        [0.8711, 0.2764, 0.6809, 0.9704, 0.9167, 0.1445, 0.0832],
        [0.3072, 0.1430, 0.2384, 0.7627, 0.7464, 0.6441, 0.1994],
        [0.7502, 0.7548, 0.6647, 0.0067, 0.1854, 0.3681, 0.2833],
        [0.4707, 0.1292, 0.0710, 0.9599, 0.5366, 0.2726, 0.0078],
        [0.1190, 0.7893, 0.6908, 0.0957, 0.6306, 0.2298, 0.3435]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
tensor_2 = torch.rand((1, 7))

# Perform matrix multiplication
tensor @ tensor_2.T

tensor([[1.1280],
        [0.7010],
        [1.3183],
        [0.9200],
        [1.5565],
        [1.3274],
        [1.1975]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_1 = torch.rand((7, 7))
tensor_2 = torch.rand((1, 7))

# Matrix multiply tensors
tensor_1 @ tensor_2.T

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [8]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()

# Create two random tensors on GPU
torch.manual_seed(1234)
tensor_gpu_1 = torch.rand((2, 3), device="cuda")
tensor_gpu_2 = torch.rand((2, 3), device="cuda")
tensor_gpu_1, tensor_gpu_2, tensor_gpu_1.device, tensor_gpu_2.device

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'),
 device(type='cuda', index=0),
 device(type='cuda', index=0))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [10]:
# Perform matmul on tensor_A and tensor_B
tensor_mult = torch.matmul(tensor_gpu_1, tensor_gpu_2.T)

### 8. Find the maximum and minimum values of the output of 7.

In [12]:
# Find max
tensor_mult.max()
# Find min
tensor_mult.max()

tensor(0.7668, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
tensor_mult.argmax()

# Find arg min
tensor_mult.argmin()


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [13]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_dim = torch.rand((1, 1, 1, 10))

# Remove single dimensions
tensor_removed_dim = tensor_dim.squeeze()

# Print out tensors and their shapes
tensor_dim, tensor_dim.shape, tensor_removed_dim, tensor_removed_dim.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 '\n',
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))